-- MySQL Script generated by MySQL Workbench
-- Wed 04 Mar 2020 11:59:21 AM +03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`users` ;

CREATE TABLE IF NOT EXISTS `mydb`.`users` (
  `identity_id` VARCHAR(32) NOT NULL,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NULL,
  PRIMARY KEY (`identity_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`money_accounts`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`money_accounts` ;

CREATE TABLE IF NOT EXISTS `mydb`.`money_accounts` (
  `id` VARCHAR(32) NOT NULL,
  `users_identity_id` VARCHAR(32) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_money_accounts_users`
    FOREIGN KEY (`users_identity_id`)
    REFERENCES `mydb`.`users` (`identity_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_money_accounts_users_idx` ON `mydb`.`money_accounts` (`users_identity_id` ASC);


-- -----------------------------------------------------
-- Table `mydb`.`transactions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`transactions` ;

CREATE TABLE IF NOT EXISTS `mydb`.`transactions` (
  `id` VARCHAR(32) NOT NULL,
  `from_money_account_id` VARCHAR(32) NOT NULL,
  `to_money_account_id` VARCHAR(32) NOT NULL,
  `amount` INT NOT NULL,
  `date` DATETIME NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_transactions_money_accounts1`
    FOREIGN KEY (`from_money_account_id`)
    REFERENCES `mydb`.`money_accounts` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_transactions_money_accounts2`
    FOREIGN KEY (`to_money_account_id`)
    REFERENCES `mydb`.`money_accounts` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_transactions_money_accounts1_idx` ON `mydb`.`transactions` (`from_money_account_id` ASC);

CREATE INDEX `fk_transactions_money_accounts2_idx` ON `mydb`.`transactions` (`to_money_account_id` ASC);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
